- name: Create vCenter VM
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_hostname: "dev-vcsa.athens.ibigroup.greece"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "1b1grVCSA!"
    vm_name: "test-vm"
    datacenter: "ATH-Datacenter"
    cluster: "MyData"
    folder: "/ATH-Datacenter/vm"
    resource_pool: "Resources"
    datastore: "DEV-ENV-VMS"
    network: "VM Network"
    image: "path/to/image.ova"

  tasks:
  - name: Connect to vCenter
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter }}"
      name: "{{ vm_name }}"
      state: poweredon
      cluster: "{{ cluster }}"
      folder: "{{ folder }}"
      resource_pool: "{{ resource_pool }}"
      esxi_hostname: "{{ cluster }}"
      networks:
        - name: "{{ network }}"
      disk:
        - size_gb: 20
          type: thin
      wait_for_ip_address: yes
      customization:
        hostname: "{{ vm_name }}"
        domain: example.com
        dns_servers:
          - 8.8.8.8
        dns_suffix: example.com
    delegate_to: localhost
